### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by SqrtMinusOne** [moevm/adfmp20-caller-id#26]
Предложения по переводу

| Исходный текст                                                                           | Предложение                                                                         |
|------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| Main Activity                                                                            | General                                                                             |
| Read Call Log permission required for app work                                           | Access to the call log is required                                                  |
| Don’t search for numbers from Contacts. Read Contacts permisson required for app work    | Do not detect numbers from the contact list. Access to the contact list is required |
| Set maximum search timeout for incoming call (in seconds)                                | Set maximum search timeout for the incoming call (in seconds)                       |
| Block notification                                                                       | “Blocked” notification?                                                             |
| Send block notification after a spam call                                                | Send “Blocked” notification after a spam call?                                      |
| Notification when ringing                                                                | Call notification                                                                   |
| Show notification istead of popup when ringing                                           | Show notification istead of popup during the incoming call                          |
| No cache empty phones                                                                    | Do not save unknown numbers                                                         |
| Don’t save in database empty phones                                                      | Do not save unrecongized numbers in the database                                    |
| Use always network                                                                       | Always use network                                                                  |
| Always use only received information from the network and ignore cached data about phone | Use only network data; ignore the database                                          |
| Spam call for 12 latest month                                                            | Spam call for the last 12 months                                                    |
| Notification Activity                                                                    | Notifications                                                                       |

**Comment by kovinevmv** [comment]
[Fix](https://github.com/moevm/adfmp20-caller-id/commit/0a875f35777dbc272a5c76f05aeccdb723190469)

[New release](https://github.com/moevm/adfmp20-caller-id/releases/tag/v.1.2)
